export const noteFields = [
 ['problem','The problem','What could earlier methods not do?'],
 ['idea','The central idea','Explain it in one sentence, then in your own words.'],
 ['equation','Equation & shapes','Write the objective; define symbols and tensor dimensions.'],
 ['evidence','Evidence','Record a table or figure, dataset, metric and comparison.'],
 ['limitations','Limitations','What remains untested? Which assumptions might fail?'],
 ['connection','Research connection','Connect to noisy text, Indic languages, vision or a new experiment.'],
 ['questions','Interview questions','Write questions you cannot yet answer.'],
 ['summary','My one-page summary','Synthesize the paper after reading it. Keep author claims separate from your interpretation.'],
] as const;
export const guides:Record<string,{idea:string;mechanism:string;equation:string;limitation:string;question:string;answer:string}>={
 bengio:{idea:'Learn a distributed representation for each word jointly with a model that predicts the next word.',mechanism:'Context words are mapped to learned vectors, concatenated and passed through a neural network to a vocabulary distribution. Similar contexts can share statistical strength through the embedding space.',equation:'p(wₜ | wₜ₋₁, …, wₜ₋ₙ₊₁); optimize the log likelihood of observed words.',limitation:'This is a fixed-context model. Its vocabulary output layer is expensive, and its word representations are not contextual token embeddings.',question:'How can learned word vectors help with unseen word combinations?',answer:'Similar words acquire nearby representations. Shared network parameters can then generalize from observed contexts to related combinations, instead of treating every n-gram as unrelated.'},
 word2vec1:{idea:'Learn useful word vectors with inexpensive prediction tasks: CBOW predicts a center word from context; Skip-gram predicts context words from a center word.',mechanism:'The models use a shared word projection and avoid the expensive nonlinear hidden layer of earlier neural language models. The learned vectors are evaluated for syntactic and semantic relationships.',equation:'CBOW: context → center. Skip-gram: center → context. Learn parameters that raise the probabilities of observed training pairs.',limitation:'These are static word vectors: one word type has the same input vector in different sentences. Negative sampling is developed in the second Word2Vec paper, scheduled next week.',question:'Is a CBOW embedding contextual because it is trained on context?',answer:'No. Context supplies the training signal, but after training a word type has a fixed lookup vector. A contextual model computes different representations for different occurrences.'},
 lenet:{idea:'Learn visual features with local receptive fields and shared weights, using a document-recognition task to motivate the architecture.',mechanism:'Convolution and subsampling progressively transform an image into features for classification. Weight sharing reduces parameters and exploits repeated visual patterns.',equation:'A shared filter computes the same weighted local operation at each spatial position.',limitation:'The original system concerns constrained document recognition. Its results do not establish unrestricted natural-scene robustness.',question:'Does convolution make a classifier automatically invariant to translation?',answer:'No. Convolution is approximately translation equivariant away from boundary and sampling effects. Pooling and later operations can provide some invariance, but it is not an automatic guarantee.'}
};
