"""Original study prompts; resource links point to their authors' free material."""
import json
from resource_catalog import augment
from pathlib import Path
# subject | id | title | resource section | fast outcome | deep exercise | coding task | spoken questions (semicolon-separated)
rows='''ML|linear-algebra|Vectors, matrices and tensor shapes|Linear algebra; matrix factorization|Explain a matrix product with all dimensions|Multiply a 2×3 matrix by a 3×2 matrix and interpret rank|Check reshape, transpose and broadcasting on small tensors|What does each axis represent?;When is a matrix non-invertible?;How is a dot product different from elementwise multiplication?
ML|probability|Probability, Bayes and uncertainty|Probability; Naive Bayes; calibration|Distinguish likelihood, prior and posterior|Compute a posterior for a rare event and explain the base-rate effect|Simulate a classifier under two class prevalences|Why is P(A given B) not P(B given A)?;What assumptions does Naive Bayes make?;What does a confidence interval cover?
ML|regression|Linear and logistic regression|Linear models; logistic regression|Compare prediction, loss and decision boundary|Derive squared-error and logistic-loss gradients|Implement both gradients and check with finite differences|Why use cross-entropy for classification?;What does a coefficient mean?;Does logistic regression fit a linear probability function?
ML|generalization|Generalization, regularization and evaluation|Model selection; cross-validation; metrics|Diagnose underfitting, leakage and misleading accuracy|Construct stratified and group-based splits and compare their assumptions|Build a preprocessing pipeline fitted only on training folds|Why can a high test score be misleading?;How do L1 and L2 differ?;When is PR more useful than ROC?
ML|svm|Margins, kernels and nearest neighbours|Support vector machines; nearest neighbours|Compare local voting with maximum-margin classification|Draw a soft-margin objective and reason about C and feature scaling|Compare linear SVM and kNN on scaled and unscaled data|What is a support vector?;What does the kernel trick avoid computing?;How does k change variance?
ML|ensembles|Trees, bagging and boosting|Decision trees; ensembles|Explain why averaging and sequential correction differ|Calculate one impurity reduction and trace one boosting update|Compare a tree, random forest and gradient boosting on identical folds|Why can trees overfit?;How does bagging reduce variance?;Why does boosting need regularization?
ML|pca-clustering|PCA, clustering and latent structure|Clustering; PCA; Gaussian mixtures|Contrast variance preservation with clustering|Compute centered covariance and one principal direction|Plot PCA and k-means with and without feature scaling|Why center before PCA?;What objective does k-means minimize?;How is a mixture posterior different from a hard assignment?
DL|backprop|Computational graphs and backpropagation|Forward/backward propagation; autograd|Trace local derivatives through a graph|Derive gradients for a two-layer scalar network|Compare manual gradients, autograd and finite differences|Why do gradients add at a branch?;What is a vector-Jacobian product?;When do gradients vanish?
DL|optimization|SGD, momentum, Adam and learning rates|Optimization algorithms|Compare the state tracked by three optimizers|Perform two momentum updates by hand|Plot training loss for several learning rates with a fixed seed|Why use minibatches?;What does Adam normalize?;Why can a small training loss coexist with poor generalization?
DL|regularization|Initialization, dropout and normalization|Initialization; dropout; batch normalization|Explain the training/inference differences|Calculate BatchNorm statistics and contrast LayerNorm axes|Inspect activations and gradients with different initializations|Which axes does each normalization use?;Why scale dropout at training time?;Does BatchNorm always fix covariate shift?
DL|convolution|Convolutions and receptive fields|Convolutional networks; padding and stride|Calculate output shape and parameter count|Trace receptive field growth through strided convolutions|Verify shapes using Conv2d and adaptive pooling|Why are weights shared?;Does a CNN require a fixed image size?;Which operation can impose a fixed-size requirement?
DL|residual|Residual networks and architecture tracing|Residual networks; modern CNNs|Draw a residual block including shape changes|Differentiate an identity skip path and a projection skip|Hook a small ResNet and log stage shapes|Why can a skip help optimization?;When is a projection required?;How does global pooling permit variable spatial dimensions?
DL|sequence|RNNs, LSTMs and sequence learning|Recurrent networks; LSTM; encoder-decoder|Explain hidden state and the LSTM gates|Unroll three time steps and identify shared parameters|Pack variable-length sequences and inspect hidden-state shapes|How does BPTT differ from ordinary backprop?;Why have a cell state?;What does teacher forcing change?
DL|training-loop|PyTorch training and debugging|Learn the Basics: tensors, autograd and optimization|Explain every line in a training step|Overfit a tiny batch before scaling up|Write train/eval loops with zero_grad, backward and optimizer.step|Why call model.eval()?;Does no_grad set evaluation mode?;How would you find a silent shape bug?
NLP|embeddings|Word2Vec, CBOW and contextual embeddings|Word embeddings; pretraining|Contrast lookup vectors with context-dependent states|Write skip-gram and negative-sampling objectives with dimensions|Build context-target pairs and train a tiny embedding table|What does CBOW predict?;Why negative sampling?;Why can one word have different contextual vectors?
NLP|tokenization|BPE, subwords and multilingual tokenization|Tokenizers; subword embedding|Trace text to IDs, masks and embeddings|Perform BPE merges on a small corpus|Compare token counts for English and Indic text using a fixed tokenizer|What does vocabulary size trade off?;Why is a token not necessarily a word?;How does tokenization affect effective context length?
NLP|attention|Attention, masks and tensor shapes|Attention; multi-head attention|Explain Q, K and V with one numerical example|Calculate scaled scores, masked softmax and weighted values|Implement a tiny attention layer and compare against a reference|Why divide by square root of head dimension?;How do causal and padding masks differ?;Where do multiple heads get their parameters?
NLP|positions|Positional encodings, RoPE and ALiBi|Self-attention and positional encoding; position methods|Explain why position information is needed|Apply a 2D rotary transform and inspect relative dot products|Test position-dependent outputs and document the model version|What is permutation equivariance?;Does RoPE change token count?;Why is length extrapolation not guaranteed?
NLP|objectives|BERT, GPT and encoder-decoder objectives|Language modelling; BERT; Transformer families|Compare visible context and prediction targets|Write the likelihood factorization and masks for each family|Inspect labels and shifted logits for a causal language model|Why is BERT not a standard autoregressive decoder?;What does T5 reconstruct?;How do pretraining and fine-tuning differ?
NLP|decoding|Decoding, perplexity and text metrics|Language models; beam search; evaluation|Contrast greedy, beam and sampling strategies|Calculate sequence log probability and a CER/WER alignment|Implement edit distance and compare two decoding settings|Can beam search reduce diversity?;Why compare perplexity only with compatible tokenization?;Can WER exceed 100 percent?
NLP|adaptation|Instruction tuning, LoRA and preference learning|LLM fine-tuning; adaptation|Separate supervised tuning from preference optimization|Count LoRA parameters and derive a low-rank weight update|Inspect trainable parameters and construct a held-out task evaluation|What remains frozen in LoRA?;Why can preference data encode bias?;How do you check catastrophic forgetting?
CV|image-processing|Filtering, sampling and image transforms|Image formation; image processing|Explain convolution, resampling and aliasing|Convolve a tiny image and examine downsampling with and without filtering|Compare blur, gradients and resizing on a checkerboard|Why low-pass before downsampling?;What is convolution versus correlation?;How does boundary padding alter an image?
CV|fourier|Fourier transforms and frequency reasoning|Image processing: Fourier analysis|Interpret low and high spatial frequencies|Calculate a small DFT and connect convolution to multiplication|Reconstruct an image after masking frequency bands|What does a Fourier coefficient represent?;Why does a sharp edge contain high frequencies?;What information is lost by discarding phase?
CV|sift|Corners, SIFT and matching|Feature detection and matching|Trace detection, orientation and descriptor construction|Explain scale-space extrema and a descriptor histogram|Match local features and filter correspondences with a ratio test|How does SIFT gain scale robustness?;Why assign orientation?;Why is a descriptor different from a detector?
CV|geometry|Camera geometry, homographies and RANSAC|Image formation; alignment; structure from motion|Distinguish affine, projective and 3D transforms|Map points with homogeneous coordinates and count degrees of freedom|Fit a homography with outliers and compare least squares with RANSAC|When does a homography describe two views?;Why divide by the homogeneous coordinate?;How do inlier ratio and sample size affect RANSAC?
CV|detection|Detection, IoU, NMS and AP|Object detection|Compare one-stage, two-stage and set-prediction detectors|Calculate IoU and trace precision-recall under score thresholds|Implement NMS on five boxes and explain a failure case|Why is IoU not AP?;What problem does NMS solve?;How does DETR use matching during training?
CV|segmentation|Segmentation, U-Net and promptable masks|Semantic segmentation; recognition|Contrast semantic, instance and panoptic outputs|Trace U-Net skip connections and calculate Dice on a toy mask|Compare per-pixel accuracy and IoU on an imbalanced mask|Why combine coarse and fine features?;Can background dominate accuracy?;What changes when segmentation is prompted?
CV|vit-ssl|ViT, contrastive learning and masked image modelling|Transformers for vision; representation learning|Compare CNN and patch-transformer inductive biases|Count patches and attention scores at two resolutions|Inspect positional interpolation and run a frozen-feature linear probe|What stays fixed when resolution changes?;Why do contrastive methods need an objective preventing collapse?;What does a linear probe actually measure?
DSA|complexity|Asymptotic and amortized analysis|Analysis of algorithms; data structures|Distinguish worst-case, expected and amortized cost|Count operations in nested loops and dynamic-array growth|Measure scaling without confusing constants with asymptotics|Is average-case the same as amortized?;Why is binary search logarithmic?;What assumptions enter a complexity claim?
DSA|arrays-hashing|Arrays, hashing and two pointers|Arrays; hashing|Choose between contiguous storage and hash lookup|Trace collisions and prove a two-pointer invariant|Implement a hash-based frequency counter and a two-sum variant|Why is hash lookup not always constant time?;What does load factor change?;When do two pointers fail?
DSA|stacks-queues|Stacks, queues and linked structures|Data structures|Explain FIFO, LIFO and pointer ownership|Trace a monotonic stack and account for each push and pop|Implement balanced-bracket checking and a queue using two stacks|Why is a monotonic stack linear overall?;When is a linked list useful?;How would you detect a cycle?
DSA|sorting-search|Sorting, binary search and invariants|Sorting; divide and conquer|Compare merge sort, quicksort and heapsort|Write and prove a binary-search loop invariant|Implement lower_bound and test empty and duplicate inputs|What makes a sort stable?;Why can quicksort be quadratic?;What exactly does your binary-search interval mean?
DSA|trees-heaps|Trees, heaps and balanced search|Binary trees; heaps|Contrast a heap with a binary search tree|Trace traversals, heap insertion and an AVL rotation|Implement a top-k heap and compare with sorting|Why is a heap not fully sorted?;What limits BST search cost?;How do you validate a BST beyond parent-child checks?
DSA|graphs|Graph traversal and shortest paths|Graph algorithms; shortest paths|Choose BFS, DFS, Dijkstra or Bellman-Ford|Run each algorithm on a small counterexample graph|Implement BFS distances and Dijkstra with stale-entry handling|When does BFS find shortest paths?;Why can Dijkstra fail with negative edges?;How do you detect a directed cycle?
DSA|dp-greedy|Dynamic programming and greedy proofs|Dynamic programming; greedy algorithms|Distinguish an optimal substructure from a greedy choice|Derive edit-distance states, transitions and base cases|Implement edit distance and reconstruct an alignment|Why is memoization not enough without a correct state?;How do you prove a greedy choice?;Give a case where greedy fails.
DBMS|relational|Relational model, keys and algebra|Chapters 2 and 27: relational model and algebra|Explain relations, keys and integrity constraints|Translate a join and projection into relational algebra|Create a small schema with primary and foreign keys|How do candidate and primary keys differ?;What does referential integrity prevent?;Is a relation mathematically ordered?
DBMS|sql|SQL joins, grouping and NULL|Chapters 3–5: SQL|Predict inner and outer join outputs|Evaluate joins and aggregates on tables containing NULL|Write joins, HAVING and a window-function ranking query|How does WHERE differ from HAVING?;Why can a join multiply rows?;What happens when NULL is compared with equals?
DBMS|normalization|Functional dependencies and normalization|Chapters 6–7: design|Recognize insertion, update and deletion anomalies|Compute attribute closure and test a decomposition for losslessness|Normalize a small enrolment schema and preserve useful constraints|What is a functional dependency?;How do 3NF and BCNF differ?;Can decomposition lose dependency preservation?
DBMS|indexes|B+ trees, hashing and storage|Chapters 12–14: storage and indexing|Choose an index for equality versus range queries|Trace a B+ tree lookup and estimate page reads|Compare EXPLAIN output with and without a suitable index|Why do databases favor high fan-out?;Why can an index hurt writes?;Why might an optimizer ignore an index?
DBMS|query-planning|Query processing and optimization|Chapters 15–16: query processing|Explain logical versus physical query plans|Compare nested-loop, hash and sort-merge join costs|Inspect cardinality estimates and actual row counts|Why does join order matter?;How can bad estimates hurt a plan?;What changes when a hash table does not fit memory?
DBMS|transactions|Transactions, isolation and concurrency|Chapters 17–18: transactions|Explain ACID with a concrete anomaly|Construct a precedence graph and compare isolation levels|Reproduce a lost update with two local database sessions|Is serializable the same as literally serial?;How do locking and MVCC differ?;Can snapshot isolation allow write skew?
DBMS|recovery|Recovery, logs and distributed transactions|Chapters 19 and 23: recovery|Explain write-ahead logging and commit boundaries|Trace a crash before and after commit and decide what to redo|Document a recovery experiment on a disposable database|Why must a log record reach durable storage first?;How do undo and redo differ?;Why can two-phase commit block?
CN|layers|Layers, packet flow and delay|Chapter 1: introduction|Trace an application message through the Internet stack|Compute transmission, propagation and serialization delays|Draw a packet journey with addresses at each hop|Why are layers useful?;How do throughput and latency differ?;Which addresses change at a router?
CN|application|HTTP, DNS and application protocols|Chapter 2: application layer|Explain what happens after entering a URL|Trace recursive and iterative DNS with caching|Inspect DNS and HTTP headers using browser developer tools|Why does DNS cache?;How do connection reuse and caching affect latency?;What does HTTPS add to HTTP?
CN|transport|UDP, TCP and reliable delivery|Chapter 3: transport layer|Explain ports, sequence numbers and acknowledgements|Trace loss, retransmission and duplicate ACKs|Inspect a TCP trace or simulate stop-and-wait delivery|Why is TCP a byte stream?;How do reliability and ordering differ?;When is UDP useful?
CN|congestion|Flow control, congestion and RTT|Chapter 3: congestion control|Distinguish receiver capacity from network capacity|Trace a congestion window and estimate timeout from RTT samples|Plot throughput under a bandwidth-delay-product model|Why is flow control not congestion control?;What causes a retransmission timeout?;Can adding buffers increase latency?
CN|subnetting|IP addressing, CIDR and subnetting|Chapter 4: subnet addressing|Find network boundaries and longest-prefix matches|Split a /24 into four /26 blocks; list address ranges|Use Python ipaddress to check manually calculated networks|What does a prefix length mean?;Why does longest-prefix matching win?;Why do /31 links differ from the usual host-count rule?
CN|routing|Routing, forwarding and NAT|Chapters 4–5: network layer|Separate control-plane routes from packet forwarding|Run distance-vector and link-state updates on a small network|Simulate route updates after a link failure|How does NAT alter addressing?;Why can distance vector count to infinity?;What differs between interdomain and intradomain routing?
CN|link-security|Ethernet, ARP and network security basics|Chapters 6 and 8: link layer and security|Trace local delivery and distinguish encryption from authentication|Follow ARP, switch learning and encapsulation for one packet|Annotate a safe local capture without collecting others’ traffic|How does a switch learn?;Why is ARP needed with IP?;What does TLS authenticate and what metadata remains visible?
Advanced|vlm-inputs|VLM input processing and variable resolution|Qwen2-VL: processor, resolution and visual tokens|Separate image dimensions, patch size, width and token count|For a specified processor, calculate resized grid, merged tokens and batch masks|Log processor output shapes for two aspect ratios; pin the checkpoint and library version|Does variable token count imply variable embedding width?;Where are resize, merge and padding applied?;Why should you not generalize one Qwen version to every VLM?
Advanced|rag|Retrieval-augmented generation and grounding|Retrieval; agents and tools|Distinguish retrieval failure from answer-generation failure|Define recall@k and an answer-support evaluation|Build a tiny retrieval baseline and inspect missed evidence|Why can high retrieval recall coexist with a wrong answer?;How does chunk size change retrieval?;How do you test whether a citation supports a claim?
Advanced|agents|Agents, tools, state and workflows|Agents course; building effective agents|Trace a tool call and its returned observation|Draw a bounded loop with state, retry budget and stopping rules|Implement a deterministic mock tool loop before attaching any model|When is a fixed workflow enough?;Where does state persist?;How do you evaluate an agent beyond its final sentence?
Advanced|llm-systems|KV cache, GQA, MoE and efficient inference|Transformer internals; inference|Separate prefill from decode and arithmetic from memory traffic|Calculate KV cache size for a stated number of layers and KV heads|Inspect configuration fields and estimate memory before a run|How does GQA change cache size?;Why does FlashAttention remain exact attention?;Why are active and total MoE parameters different?
Advanced|generative|VAE, GAN and diffusion objectives|Generative modelling|Compare latent-variable, adversarial and denoising training|Write an ELBO and explain each term; trace one noising step|Simulate forward diffusion on a tiny array|Why is the ELBO a lower bound?;What does the discriminator learn?;How do training noise prediction and iterative sampling relate?
Advanced|ocr-research|OCR, Indic text and error analysis|Text evaluation; research design|Separate recognition, correction and normalization errors|Calculate CER/WER and stratify errors by script and document source|Build a small error taxonomy and compare a simple correction baseline|How can normalization change your metric?;What would prove a correction method hallucinates?;What split avoids document-level leakage?
Advanced|research-defence|Research defence, teaching and experimental design|Research synthesis; evaluation|Give a two-minute claim, evidence and limitation narrative|Design an ablation with a falsifiable hypothesis and matched budget|Reproduce one small baseline and log seeds, versions and uncertainty|What is your contribution beyond a stronger baseline?;What observation would falsify your explanation?;How would you teach this to a second-year student?
'''
resources={
'ML':[('Stanford CS229','https://cs229.stanford.edu/','Course notes / theory'),('scikit-learn user guide','https://scikit-learn.org/stable/user_guide.html','Implementation reference')],
'DL':[('Dive into Deep Learning','https://d2l.ai/','Free textbook / worked code'),('PyTorch: Learn the Basics','https://docs.pytorch.org/tutorials/beginner/basics/intro.html','Hands-on tutorial')],
'NLP':[('Stanford CS224N','https://web.stanford.edu/class/cs224n/','Lectures / notes'),('Hugging Face LLM course','https://huggingface.co/learn/llm-course/chapter1/1','Free implementation course')],
'CV':[('Szeliski: Computer Vision','https://szeliski.org/Book/','Author-provided textbook'),('Stanford CS231n','https://cs231n.stanford.edu/','Deep vision course')],
'DSA':[('MIT 6.006','https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/','Lectures / exercises'),('Jeff Erickson: Algorithms','https://jeffe.cs.illinois.edu/teaching/algorithms/','Free textbook / proofs')],
'DBMS':[('Database System Concepts: slides','https://www.db-book.com/slides-dir/index.html','Free chapter slides'),('PostgreSQL tutorial','https://www.postgresql.org/docs/current/tutorial.html','SQL practice; use documentation search for internals')],
'CN':[('Kurose–Ross online lectures','https://gaia.cs.umass.edu/kurose_ross/online_lectures.htm','Free lectures'),('Kurose–Ross interactive problems','https://gaia.cs.umass.edu/kurose_ross/interactive/','Worked practice; security not covered by every exercise')],
'Advanced':[('Hugging Face LLM course','https://huggingface.co/learn/llm-course/chapter1/1','Implementation foundations'),('Dive into Deep Learning','https://d2l.ai/','Mathematical foundations')]
}
overrides={
'linear-algebra':[('D2L: linear algebra','https://d2l.ai/chapter_preliminaries/linear-algebra.html','Read and work the tensor examples')],
'probability':[('D2L: probability','https://d2l.ai/chapter_preliminaries/probability.html','Read conditional probability and expectations')],
'positions':[('RoFormer paper','https://arxiv.org/abs/2104.09864','Study the rotary construction'),('ALiBi paper','https://arxiv.org/abs/2108.12409','Compare additive attention bias')],
'vlm-inputs':[('Qwen2-VL documentation','https://huggingface.co/docs/transformers/en/model_doc/qwen2_vl','Processor settings and image token budgets'),('Qwen2-VL technical report','https://arxiv.org/abs/2409.12191','Architecture evidence; a versioned example, not a latest-model claim')],
'agents':[('Hugging Face agents course','https://huggingface.co/learn/agents-course/unit0/introduction','Tools, observations and agent loop'),('Anthropic: building effective agents','https://www.anthropic.com/engineering/building-effective-agents','Compare workflow patterns and agent loops')],
'rag':[('RAG paper','https://arxiv.org/abs/2005.11401','Original retrieval/generation formulation'),('Hugging Face agents course','https://huggingface.co/learn/agents-course/unit0/introduction','Connect retrieval with tool-based systems')],
'generative':[('D2L: generative modelling','https://d2l.ai/','GAN chapters'),('DDPM paper','https://arxiv.org/abs/2006.11239','Denoising objective and sampling algorithm')],
'ocr-research':[('TrOCR paper','https://arxiv.org/abs/2109.10282','Recognition baseline and training setup'),('Stanford CS224N','https://web.stanford.edu/class/cs224n/','Language modelling and evaluation background')],
'research-defence':[('scikit-learn evaluation guide','https://scikit-learn.org/stable/user_guide.html','Model selection, metrics and leakage checks'),('Stanford CS224N','https://web.stanford.edu/class/cs224n/','Project and research communication resources')]
}
topics=[]
for line in rows.strip().splitlines():
 subject,id,title,section,fast,deep,code,drills=line.split('|')
 rr=resources[subject]
 if id in overrides: rr=overrides[id] if subject=='Advanced' else overrides[id]+rr
 topics.append(dict(id=id,subject=subject,title=title,section=section,fast=fast,deep=deep,code=code,drills=drills.split(';'),core=id in ['linear-algebra','probability','embeddings','positions','sift','fourier','image-processing','subnetting','attention','backprop'],resources=[dict(title=a,url=b,use=c) for a,b,c in rr]))
topics=augment(topics)
assert len(topics)==56
Path('hub/topics.json').write_text(json.dumps(topics,ensure_ascii=False,indent=2)+'\n')
print(len(topics),'topics')
