export type Exercise={title:string;prompt:string;answer:number;unit:string;steps:string;transfer:string};
export function exercise(kind:number,variant=0):Exercise{
 const a=variant%5+1;
 const bank:Exercise[]=[
 {title:'Dot product',prompt:`x=[${a},2], w=[3,-1]. Compute x·w.`,answer:3*a-2,unit:'',steps:`Multiply matching entries and sum: ${a}×3 + 2×(-1) = ${3*a-2}.`,transfer:'Where does a dot product appear in a neuron and in attention?'},
 {title:'One gradient step',prompt:`Prediction is wx, x=2, target=3, w=${a}. L=½(wx−3)². Find dL/dw.`,answer:4*a-6,unit:'',steps:`Chain rule: dL/dw=(wx−3)x=(${a}×2−3)×2=${4*a-6}.`,transfer:'Use learning rate 0.1 to update w. Compare the loss before and after.'},
 {title:'Bayes on a small dataset',prompt:'20 of 100 tokens contain errors. A flagger flags 16 erroneous and 8 correct tokens. What percentage of flagged tokens really contain errors?',answer:100*16/24,unit:'%',steps:'There are 24 flagged tokens. Precision=P(error|flag)=16/24=66.67%. Recall is a different quantity: 16/20.',transfer:'What happens to precision if the same detector is used where errors are rarer?'},
 {title:'Softmax probability',prompt:`Two logits are [0, ln(${a+1})]. What is the probability of the second class?`,answer:(a+1)/(a+2),unit:'',steps:`Exponentials are [1,${a+1}]. Normalize by ${a+2}: p₂=${a+1}/${a+2}.`,transfer:'Add 100 to both logits. Explain why the distribution is unchanged.'},
 {title:'Binary cross-entropy',prompt:'The correct binary label is 1 and its predicted probability is 0.5. Compute the loss using natural logarithms.',answer:Math.log(2),unit:'nats',steps:'L=−[y ln p+(1−y)ln(1−p)]=−ln(0.5)=ln2≈0.6931.',transfer:'How does the gradient behave if you differentiate with respect to the logit rather than the probability?'},
 {title:'Dense-layer parameters',prompt:`A linear layer has ${a+2} inputs and 4 outputs, with a bias. How many trainable scalars?`,answer:(a+2)*4+4,unit:'parameters',steps:`W has 4×${a+2} entries; b has 4. Total ${(a+2)*4+4}. Batch size does not change the parameter count.`,transfer:'Write the input, weight and output shapes for batch size 8.'},
 {title:'Convolution output size',prompt:`A square input has side ${28+2*a}; kernel=3, stride=2, padding=1, dilation=1. What is the output side length?`,answer:14+a,unit:'pixels',steps:`floor((H+2P−D(K−1)−1)/S+1)=floor((${28+2*a}+2−2−1)/2+1)=${14+a}.`,transfer:'Why must we take the floor? Verify with a PyTorch tensor.'},
 {title:'Convolution parameters',prompt:`Conv2d has 3 input channels, ${a+3} output channels, 3×3 kernels and one bias per output channel. Count parameters.`,answer:28*(a+3),unit:'parameters',steps:`Each output channel uses 3×3×3 weights plus one bias: 28. Total 28×${a+3}=${28*(a+3)}.`,transfer:'Why is this independent of image width and height?'},
 {title:'Receptive field',prompt:'Two consecutive 3×3 stride-1 convolutions, no dilation. What is the receptive-field side length of a second-layer feature?',answer:5,unit:'pixels',steps:'First layer sees 3 pixels per axis. Second adds 2: r₂=3+(3−1)×1=5.',transfer:'Recalculate when the first convolution has stride 2.'},
 {title:'Residual gradient',prompt:`y=x+${a}x². Find dy/dx at x=1.`,answer:1+2*a,unit:'',steps:`dy/dx=1+2×${a}×x. At 1, the identity path contributes 1 and the residual path contributes ${2*a}.`,transfer:'Why does an identity path help optimization without guaranteeing perfect gradients?'},
 {title:'CBOW context average',prompt:`Two context embeddings are [${a},2] and [3,4]. What is the first component of their mean?`,answer:(a+3)/2,unit:'',steps:`Mean=([${a},2]+[3,4])/2=[${(a+3)/2},3]. This is a representation, not yet a vocabulary probability.`,transfer:'What computation maps this vector to a prediction over words?'},
 {title:'Scaled attention score',prompt:`q=[${a},1], k=[2,0]. With dₖ=2, compute q·k/√dₖ.`,answer:2*a/Math.sqrt(2),unit:'',steps:`q·k=2×${a}; divide by √2 to obtain ${(2*a/Math.sqrt(2)).toFixed(4)}. Softmax happens across all allowed keys.`,transfer:'Compute scores for a second key and normalize them jointly.'},
 {title:'Attention-weighted value',prompt:`Attention weights=[0.25,0.75], scalar values=[${a},4]. Find the weighted output.`,answer:.25*a+3,unit:'',steps:`0.25×${a}+0.75×4=${.25*a+3}.`,transfer:'If weights depend on the query, why is this more flexible than fixed average pooling?'},
 {title:'Causal attention mask',prompt:`For a sequence of ${a+2} tokens, including self-attention, how many query-key pairs are allowed by a causal mask?`,answer:(a+2)*(a+3)/2,unit:'pairs',steps:`Row i can see i positions. Sum 1…n=n(n+1)/2=${(a+2)*(a+3)/2}.`,transfer:'Distinguish causal masking from masking padding positions.'},
 {title:'Patch grid',prompt:`An image is ${224*a}×224, patch size is 16×16, with no class token or merging. How many patches?`,answer:196*a,unit:'patches',steps:`(${224*a}/16)×(224/16)=${14*a}×14=${196*a}.`,transfer:'Which quantity changes with image resolution: patch size, embedding width or token count?'},
 {title:'Spatial token merging',prompt:`A processed image is ${112*a}×224. Patch size=14; each 2×2 patch group becomes one token. Count merged tokens, excluding special tokens.`,answer:32*a,unit:'tokens',steps:`Raw grid=${8*a}×16, then divide count by 4: ${128*a}/4=${32*a}. This is a specified toy configuration.`,transfer:'Measure what happens to small text as resolution or merging changes.'},
 {title:'Attention scaling',prompt:`Sequence length grows from n to ${a+1}n. Holding width fixed, by what factor does the number of dense attention scores grow?`,answer:(a+1)**2,unit:'times',steps:`The score matrix is n×n; new area is (${a+1}n)²=${(a+1)**2}n². This is not a claim about whole-model latency.`,transfer:'Which costs are linear in sequence length? How can implementation change memory usage?'},
 {title:'LoRA parameter budget',prompt:`A 16×8 weight matrix uses LoRA rank ${a}. How many parameters are in A and B together, ignoring biases?`,answer:24*a,unit:'parameters',steps:`A is r×8 and B is 16×r: r(8+16)=24×${a}=${24*a}.`,transfer:'Compare with the original 128 weights. At what rank is this no longer a parameter saving?'},
 {title:'Word error rate',prompt:`Reference has 20 words, substitutions=${a}, deletions=2, insertions=1. Compute WER as a percentage.`,answer:(a+3)*5,unit:'%',steps:`WER=(S+D+I)/N×100=(${a}+2+1)/20×100=${(a+3)*5}%.`,transfer:'Construct an example where WER exceeds 100%. Explain why.'},
 {title:'Intersection over union',prompt:'Two boxes each have area 12 and their intersection has area 4. Compute IoU.',answer:.2,unit:'',steps:'Union=12+12−4=20. IoU=4/20=0.2.',transfer:'Why is IoU not enough to define dataset-level average precision?'},
 {title:'Retrieval recall',prompt:`There are 10 relevant documents; top-k retrieval returns ${a} relevant ones. What is recall@k as a percentage?`,answer:a*10,unit:'%',steps:`Recall@k=relevant retrieved / all relevant=${a}/10=${a*10}%. The value of k must be at least ${a}.`,transfer:'Why can high retrieval recall coexist with poor final answers?'},
 {title:'Pipeline reliability',prompt:'Three independent stages each succeed with probability 0.9. What is the probability all succeed?',answer:.729,unit:'',steps:'Under the explicit independence assumption, 0.9³=0.729. Real failures may be correlated.',transfer:'How would you detect whether failures of your agent tools are correlated?'},
 {title:'KV cache size',prompt:'A toy model has 2 layers, 1 KV head, head dimension 4 and sequence length 8. Count cached K and V scalars together for one example.',answer:128,unit:'scalars',steps:'2(K,V)×2 layers×1 head×4 dimensions×8 tokens=128. At two bytes/scalar this is 256 bytes, excluding overhead.',transfer:'Which factors change with grouped-query attention and batch size?'},
 {title:'Simple uncertainty estimate',prompt:'You observe success on 80 of 100 independent examples. Using sqrt(p(1−p)/n), estimate the standard error of accuracy.',answer:.04,unit:'',steps:'p=0.8. SE=sqrt(0.8×0.2/100)=sqrt(0.0016)=0.04. This rough formula assumes independent Bernoulli outcomes.',transfer:'Why might sentence-level independence fail for examples from the same document?'}
 ];return bank[((kind%bank.length)+bank.length)%bank.length];
}
export const exerciseCount=24;
