import {useEffect,useState} from 'react';
import Expedition from '../app/expedition';
import papers from '../lib/papers.json';
import content from './content.json';
import {START,END,prepDates,readingDates,studyDates,excluded,formatDate,dayDate,isoDate} from './calendar';
import {exercise,exerciseCount} from './exercises';
import {loadBrowserProgress,parseBackup,STORAGE_KEY} from '../lib/browser-progress';
import './hub.css';
import Topics from './Topics';
import {validateTopicFields} from './review';
const KEY='paper-expedition:learning-hub:v1';
type Data=Record<string,string|number|boolean>;
function validate(v:unknown):Data{if(!v||typeof v!=='object'||Array.isArray(v))throw Error('Invalid hub backup');for(const [k,x] of Object.entries(v)){if(!/^[a-zA-Z0-9:_-]{1,160}$/.test(k)||['__proto__','constructor','prototype'].includes(k)||!['string','number','boolean'].includes(typeof x)||(typeof x==='string'&&x.length>20000)||(typeof x==='number'&&!Number.isFinite(x)))throw Error('Invalid saved field')}validateTopicFields(v as Record<string,unknown>);return v as Data}
function download(name:string,text:string,type='application/json'){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500)}
const architectureFields=['Input and preprocessing','Tensor shapes and token counts','Core operations and mathematical objective','Training versus inference','Position, masks and batching','Code evidence and exact version','Ablation and reported evidence','Failure case and competing explanations','Hypothesis and falsifying experiment'];
const journalFields=['Observation','What the source establishes','My hypothesis','Closest related work and novelty check','Baseline and controlled variables','Smallest falsifying experiment','Result and next decision'];
const tabs=['Topics','Today','Roadmap','Papers','By hand','Architecture lab','Interviews','Research notebook','Keep going'];
export default function Hub(){
 const [data,setData]=useState<Data>({}),[error,setError]=useState(''),[loaded,setLoaded]=useState(false),[message,setMessage]=useState('');
 const [tab,setTab]=useState('Topics'),[date,setDate]=useState(START),[model,setModel]=useState('Transformer'),[journal,setJournal]=useState('idea-1');
 const [kind,setKind]=useState(0),[variant,setVariant]=useState(0),[answer,setAnswer]=useState(''),[feedback,setFeedback]=useState(''),[reveal,setReveal]=useState(false);
 const [seconds,setSeconds]=useState(900),[running,setRunning]=useState(false),[questionFilter,setQuestionFilter]=useState('All');
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);setData(raw?validate(JSON.parse(raw)):{});setLoaded(true)}catch{setError('Saved data could not be loaded. Saving is disabled to protect it. Use another browser or recover your backup.')}},[]);
 useEffect(()=>{if(!running)return;const end=Date.now()+seconds*1000;const timer=setInterval(()=>{const n=Math.max(0,Math.ceil((end-Date.now())/1000));setSeconds(n);if(n===0)setRunning(false)},500);return()=>clearInterval(timer)},[running]);
 function save(key:string,value:string|number|boolean){if(!loaded)return;try{const raw=localStorage.getItem(KEY);const latest=raw?validate(JSON.parse(raw)):{};const next={...latest,[key]:value};localStorage.setItem(KEY,JSON.stringify(next));setData(next);setError('')}catch{setError('This change was not saved: browser storage is unavailable, full or invalid. Export a backup before clearing any data.')}}
 function check(key:string,label:string){return <label className="hub-check"><input type="checkbox" disabled={!loaded} checked={data[key]===true} onChange={e=>save(key,e.target.checked)}/><span>{label}</span></label>}
 function note(key:string,label:string,placeholder='Write your explanation, evidence or question here.'){return <label className="hub-field">{label}<textarea disabled={!loaded} maxLength={20000} value={String(data[key]??'')} onChange={e=>save(key,e.target.value)} placeholder={placeholder}/></label>}
 function exportAll(){try{const raw=localStorage.getItem(KEY);download('learning-hub-backup.json',JSON.stringify({format:'learning-hub-v1',hub:raw?validate(JSON.parse(raw)):{},papers:loadBrowserProgress(localStorage,papers.map(p=>p.id))},null,2));setMessage('Backup downloaded. Keep a copy outside this browser.')}catch(e){setError(String(e))}}
 async function restore(file?:File){if(!file)return;try{if(file.size>16000000)throw Error('Backup exceeds 16 MB');const next=JSON.parse(await file.text());if(next.format!=='learning-hub-v1')throw Error('Choose a complete learning-hub backup');const hub=validate(next.hub);const paper=parseBackup(JSON.stringify(next.papers),papers.map(p=>p.id));if(!window.confirm('Replace this browser’s hub and paper progress with this backup? Download your current backup first if needed.'))return;const oldHub=localStorage.getItem(KEY),oldPaper=localStorage.getItem(STORAGE_KEY);try{localStorage.setItem(KEY,JSON.stringify(hub));localStorage.setItem(STORAGE_KEY,JSON.stringify(paper))}catch(e){if(oldHub===null)localStorage.removeItem(KEY);else localStorage.setItem(KEY,oldHub);if(oldPaper===null)localStorage.removeItem(STORAGE_KEY);else localStorage.setItem(STORAGE_KEY,oldPaper);throw e}setData(hub);setTab('Today');setLoaded(true);setError('');setMessage('Complete backup restored.')}catch(e){setError('Restore failed: '+String(e))}}
 const idx=prepDates.indexOf(date),activeIdx=readingDates.indexOf(date),lesson=idx>=0?content.lessons[idx]:null;
 const fastIndex=idx<0?0:idx%24,cycle=idx<0?1:Math.floor(idx/24)+1;
 const paperIndex=activeIdx<0?-1:Math.floor(activeIdx/2),p=paperIndex>=0?papers[paperIndex]:null;
 const interview=String(data.interviewDate??'');const untilInterview=interview?Math.round((dayDate(interview).getTime()-dayDate(date).getTime())/86400000):999;
 const interviewMode=untilInterview>=0&&untilInterview<=10;
 const ex=exercise(kind,variant);
 function selectExercise(k:number,v:number){setKind(k);setVariant(v);setAnswer('');setFeedback('');setReveal(false);setSeconds(900);setRunning(false)}
 function moveDay(offset:number){const d=dayDate(date);d.setUTCDate(d.getUTCDate()+offset);setDate(isoDate(d))}
 const finished=prepDates.filter(d=>['deep','fast','paper'].every(k=>data[d+':'+k]===true)).length;
 const maintenance=String(data.maintenance??'2');
 return <div className="learning-hub"><header className="hub-top"><a href="#" onClick={e=>{e.preventDefault();setTab('Today')}} className="hub-brand"><span>◈</span><div>Learning Expedition<small>UNDERSTAND · IMPLEMENT · QUESTION</small></div></a><div className="hub-top-right">Faculty / postdoc preparation<span>Private notes on this device</span></div></header>
 <div className="hub-banner"><div><p className="hub-kicker">SEPTEMBER 2026 — MAY 2027</p><h1>A place to build understanding.</h1><p>Deep foundations, architecture investigations and a lasting reading practice.</p></div><div className="hub-stat"><b>{finished}<span> / 86</span></b><span>preparation days completed</span><progress max={86} value={finished}/></div></div>
 <nav className="hub-nav" aria-label="Learning sections">{tabs.map(t=><button key={t} aria-current={tab===t?'page':undefined} onClick={()=>setTab(t)}>{t}</button>)}</nav>
 <main className="hub-main">{error&&<div role="alert" className="hub-alert">{error}</div>}{message&&<p role="status" className="hub-message">{message}<button onClick={()=>setMessage('')}>Dismiss</button></p>}
 {tab==='Topics'&&<Topics data={data} save={save} loaded={loaded} openHand={()=>setTab('By hand')} openArchitecture={()=>setTab('Architecture lab')}/>}
 {tab==='Today'&&<><div className="hub-section-head"><div><p className="hub-kicker">YOUR NEXT SMALL STEP</p><h2>{formatDate(date)}</h2><p>{idx>=0?`Study day ${idx+1} · ${lesson?.group}`:excluded(date)?'Protected time off — no overdue work is created.':date>END?'Continuing practice — use the Keep going routine.':'Preparation begins 22 September.'}</p></div><div className="hub-date"><button aria-label="Previous date" onClick={()=>moveDay(-1)}>←</button><input aria-label="Choose study date" type="date" value={date} min="2026-09-22" max="2027-05-31" onChange={e=>{if(e.target.value)setDate(e.target.value)}}/><button aria-label="Next date" onClick={()=>moveDay(1)}>→</button><button onClick={()=>{const d=new Date();setDate(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`)}}>Today</button></div></div>
 {interviewMode&&<div className="hub-callout">Interview preparation window: {untilInterview} days to your entered date. On study days, use the paper block for a mock, job talk or teaching rehearsal. Your breaks remain protected; finish rehearsal before a break if necessary.</div>}
 {lesson?<><div className="hub-grid three"><article className="hub-card"><span className="hub-pill">DEEP · 3 HOURS</span><h3>{lesson.title}</h3><p>{lesson.goal}</p><a href={lesson.url} target="_blank" rel="noreferrer">Free primary resource ↗</a><details><summary>How to spend the three hours</summary><p>15 min recall · 15 min by hand · 60 min learning · 40 min derivation/worked problems · 30 min coding · 20 min teach-back/error log. Coding and hand work are included, not extra.</p></details><button onClick={()=>setTab('Topics')}>Browse topics and resources →</button><h4>Code for 30 minutes</h4><p>{lesson.code}</p><button className="hub-action" onClick={()=>{selectExercise(lesson.hand,Math.floor(idx/24));setTab('By hand')}}>Open today's hand exercise →</button>{check(date+':deep','Deep session completed')}{check(date+':hand','Hand exercise completed (inside deep block)')}</article>
 <article className="hub-card"><span className="hub-pill amber">FAST TRACK · 1 HOUR</span><h3>{content.fast[fastIndex]}</h3><p>Pass {cycle}: {['define and explain the idea','trace the mechanism and compare','solve, critique and connect','repair weak concepts and teach'][Math.min(cycle-1,3)]}.</p><p>10 min closed-book recall · 35 min targeted overview · 15 min explanation aloud. If already secure, use the slot for your weakest recorded concept.</p><p>Finish with three questions you can answer without notes.</p><button onClick={()=>setTab('Topics')}>Browse topics and resources →</button>{check(date+':fast','Fast-track session completed')}</article>
 <article className="hub-card"><span className="hub-pill blue">{interviewMode?'INTERVIEW PRACTICE':'PAPER STUDY'} · 2 HOURS</span><h3>{interviewMode?'Rehearse, then repair':p?.short}</h3><p>{interviewMode?'Record a teaching demo or research defence; use the remaining time to repair the most consequential gap.':`${activeIdx%2===0?'Session 1: problem, main idea and architecture.':'Session 2: equations, evidence, limitations and recall.'} ${p?.goal??''}`}</p>{!interviewMode&&p&&<a href={p.url} target="_blank" rel="noreferrer">Read the source paper ↗</a>}<p>Paper notes and progress live in the Papers section. The schedule is a target; missed papers remain available.</p><button onClick={()=>setTab(interviewMode?'Interviews':'Papers')}>Open {interviewMode?'practice prompts':'paper library'} →</button>{check(date+':paper',interviewMode?'Interview practice completed':'Paper session completed')}</article></div>
 <div className="hub-card slim"><div><h3>Optional revision · 30 minutes</h3><button onClick={()=>setTab('Topics')}>Open topic review queue →</button><p>10 min basic concepts · 10 min architecture from memory · 10 min equations or spoken answers. Skip freely; no catch-up debt.</p><p>Revisit study days {Array.from(new Set([idx-1,idx-3,idx-6,idx-18].filter(n=>n>=0))).map(n=>`${n+1} (${content.lessons[n].title})`).join(' · ')||'None yet — begin with your diagnostic.'}.</p></div>{check(date+':revision','Optional revision done')}</div>
 <div className="hub-grid two"><article className="hub-card"><h3>What did you understand today?</h3>{note(date+':recall','Explain it without looking','Write a short explanation, one equation and a concrete example.')}</article><article className="hub-card"><h3>What remains fragile?</h3>{note(date+':gap','Error log and next action','Name the confusion and the smallest exercise that would resolve it.')}</article></div></>:<div className="hub-card"><h3>{excluded(date)?'Rest, travel or conference time.':'Continue the practice.'}</h3><p>{excluded(date)?'Sundays, 6–15 November and 15–21 December carry no required sessions.':'Deep preparation ends 15 January. Continue paper study and a sustainable concept/coding routine.'}</p>{!excluded(date)&&p&&<p>Paper target: {p.short} — {activeIdx%2===0?'first':'second'} reading session.</p>}<button onClick={()=>setTab('Keep going')}>See the continuing routine →</button></div>}
 </>}
 {tab==='Roadmap'&&<><div className="hub-section-head"><div><p className="hub-kicker">A PLAN WITH ROOM TO THINK</p><h2>86 study days through 15 January</h2><p>22 September start · Sundays off · Diwali break 6–15 November · IndoML 15–21 December.</p></div></div><div className="hub-metrics"><div><b>438 h</b><span>scheduled through 31 Dec</span></div><div><b>516 h</b><span>scheduled through 15 Jan</span></div><div><b>21.5 h</b><span>by hand inside deep study</span></div><div><b>43 h</b><span>optional revision capacity</span></div></div><div className="hub-callout">Use roughly 15% of scheduled time for repair or catch-up. October, November and December are readiness checkpoints, not booked interviews. Research and application work are outside this six-hour allocation.</div><label className="hub-field">Interview date — leave blank until scheduled<input type="date" value={interview} onChange={e=>save('interviewDate',e.target.value)}/></label><p>A date activates a 10-day preparation banner in the daily view. It redirects the paper block; it does not add hours or automatically reschedule missed papers.</p><div className="hub-roadmap">{prepDates.map((d,i)=><button key={d} className={data[d+':deep']?'done':''} onClick={()=>{setDate(d);setTab('Today')}}><span>{String(i+1).padStart(2,'0')}<small>{formatDate(d)}</small></span><div><strong>{content.lessons[i].title}</strong><small>{content.lessons[i].group}</small></div><span>{data[d+':deep']?'✓':'→'}</span></button>)}</div></>}
 {tab==='Papers'&&<><div className="hub-callout"><b>98 papers · two 2-hour sessions each · final paper target 24 May 2027.</b> The calendar excludes Sundays and both breaks. It assumes the six-hour routine; lighter maintenance will move the completion date. Existing progress stays available. The catalog's 2025 reports are a starting selection; refresh frontier papers when reached.</div><Expedition browserOnly/></>}
 {tab==='By hand'&&<><div className="hub-section-head"><div><p className="hub-kicker">PENCIL FIRST · CODE SECOND</p><h2>15 minutes, one mechanism.</h2><p>Original free exercises with worked solutions. Not copied from, or affiliated with, a paid “AI by Hand” product.</p></div><div className="hub-timer"><b>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</b><button onClick={()=>setRunning(!running)}>{running?'Pause':'Start 15-min timer'}</button><button onClick={()=>{setRunning(false);setSeconds(900)}}>Reset</button></div></div><div className="hub-grid lab"><aside className="hub-card exercise-list">{Array.from({length:exerciseCount},(_,i)=><button key={i} aria-pressed={kind===i} onClick={()=>selectExercise(i,variant)}>{String(i+1).padStart(2,'0')} · {exercise(i).title}</button>)}</aside><article className="hub-card"><span className="hub-pill">EXERCISE {kind+1} · VARIANT {variant+1}</span><h3>{ex.title}</h3><p className="hub-problem">{ex.prompt}</p><p>3 min predict · 7 min calculate · 3 min explain · 2 min check.</p><label className="hub-field">Your numerical answer {ex.unit&&`(${ex.unit})`}<input type="number" step="any" value={answer} onChange={e=>setAnswer(e.target.value)}/></label><div className="hub-buttons"><button className="hub-action" onClick={()=>{const n=Number(answer);const ok=answer.trim()!==''&&Number.isFinite(n)&&Math.abs(n-ex.answer)<=.01;setFeedback(ok?'Correct within rounding tolerance. Explain why each step works.':'Not yet. Check units and intermediate steps; reveal the solution if useful.');if(ok)save(`exercise:${kind}:${variant}`,true)}}>Check answer</button><button onClick={()=>setReveal(!reveal)}>{reveal?'Hide':'Reveal'} worked solution</button><button onClick={()=>selectExercise(kind,variant+1)}>Another variant</button></div>{feedback&&<p role="status" className="hub-callout">{feedback}</p>}{reveal&&<div className="hub-solution"><b>Worked solution</b><p>{ex.steps}</p><p><b>Answer:</b> {Number(ex.answer.toFixed(4))} {ex.unit}</p></div>}<h4>Transfer the idea</h4><p>{ex.transfer}</p>{note(`exercise-note:${kind}`,'My reasoning and remaining question')}
 <p className="hub-muted">Some conceptual exercises intentionally repeat unchanged. Numerical variants vary where meaningful. Checking verifies the final number, not your reasoning.</p></article></div></>}
 {tab==='Architecture lab'&&<><p className="hub-kicker">FROM RAW INPUT TO PREDICTION</p><h2>Investigate one architecture at a time.</h2><p>Predict → calculate → inspect code → run a small test → explain → challenge. Use one main architecture per week; give a complex VLM two weeks if needed.</p><label className="hub-field">Investigation<select value={model} onChange={e=>setModel(e.target.value)}>{['Linear model','MLP','CNN / ResNet','Word2Vec','LSTM / Seq2seq','Transformer','BERT / T5','ViT','CLIP','Qwen2-VL example','Current model investigation','Agent workflow'].map(x=><option key={x}>{x}</option>)}</select></label><div className="hub-callout">For variable-resolution images, distinguish patch size, embedding width and token count. Inspect resizing, spatial merging, positional encoding and batching separately. Do not generalize one model version to every VLM. <a href="https://huggingface.co/docs/transformers/en/model_doc/qwen2_vl" target="_blank" rel="noreferrer">Qwen2-VL reference ↗</a></div><div className="hub-grid two">{architectureFields.map((f,i)=><article className="hub-card" key={f}>{note(`arch:${model.replace(/[^a-zA-Z0-9]/g,'')}:${i}`,f,i===0?'Use a real input: original dimensions, processor settings and transformed representation.':'State the evidence, dimensions, equation or uncertainty. Add the source URL and exact version where relevant.')}</article>)}</div><p>Evidence of mastery: draw the model cold, calculate shapes on an unfamiliar input, verify a small computation and explain one failure case. Understanding every model is not a prerequisite for investigating one well.</p></>}
 {tab==='Interviews'&&<><p className="hub-kicker">EXPLAIN · DERIVE · DEFEND</p><h2>Practice before an invitation arrives.</h2><p>28 open-ended prompts with answer checklists. These are original practice questions, not predictions of a particular panel.</p><div className="hub-buttons"><select aria-label="Filter interview questions" value={questionFilter} onChange={e=>setQuestionFilter(e.target.value)}>{['All',...Array.from(new Set(content.questions.map(q=>q.area)))].map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>setQuestionFilter('Research')}>Research defence</button></div><div className="hub-callout">Weekly: a short spoken drill. Monthly: one full mock and one recorded teaching demo. When invited: inspect the actual format, tailor research fit, and replace paper hours with rehearsal during the final 10 days.</div><div className="hub-grid two">{content.questions.map((q,i)=>(questionFilter==='All'||q.area===questionFilter)&&<article className="hub-card" key={i}><span className="hub-pill">{q.area}</span><h3>{q.q}</h3>{note(`question:${i}`,'My answer','Answer aloud first, then note gaps in your explanation.')}<details><summary>Reveal answer checklist</summary><p>{q.guide}</p></details><label className="hub-field">Self-assessment<select value={String(data[`qscore:${i}`]??'Not tried')} onChange={e=>save(`qscore:${i}`,e.target.value)}>{['Not tried','Name only','Explain with notes','Explain independently','Derive / apply / critique'].map(x=><option key={x}>{x}</option>)}</select></label></article>)}</div></>}
 {tab==='Research notebook'&&<><p className="hub-kicker">TURN CURIOSITY INTO A TEST</p><h2>Keep observations separate from claims.</h2><p>A possible gap becomes a research direction only after checking prior work, ruling out simpler explanations and designing a useful experiment.</p><label className="hub-field">Notebook entry<select value={journal} onChange={e=>setJournal(e.target.value)}>{Array.from({length:12},(_,i)=><option key={i} value={`idea-${i+1}`}>Investigation {i+1}</option>)}</select></label>{note(journal+':title','Working title','For example: resolution allocation for small Indic characters')}<div className="hub-grid two">{journalFields.map((f,i)=><article className="hub-card" key={f}>{note(`${journal}:${i}`,f)}</article>)}</div><div className="hub-callout">Example hypothesis, not a novelty claim: at a matched visual-token budget, a different region-allocation policy could preserve small text better. Control checkpoint, prompts and decoding; measure token count, runtime and stratified CER/WER. Check existing work before proposing a new method.</div></>}
 {tab==='Keep going'&&<><p className="hub-kicker">A PRACTICE THAT CAN SURVIVE A NEW JOB</p><h2>Continue after January.</h2><p>The full paper route runs through May. Choose a workload that leaves room for research, applications and your future role.</p><label className="hub-field">Continuing study budget<select value={maintenance} onChange={e=>save('maintenance',e.target.value)}><option value="2">2 hours per study day</option><option value="4">4 hours per study day</option><option value="6">6 hours per study day</option></select></label><div className="hub-card"><h3>{maintenance}-hour routine</h3><p>{maintenance==='2'?'15 min by hand · 45 min concept study or coding (alternate days) · 45 min paper study · 15 min recall. Aim for about one substantial paper per week; May is no longer a guaranteed finish.':maintenance==='4'?'15 min by hand · 75 min deep concept/coding · 120 min papers · 30 min retrieval/interview practice. The original paper pace can continue if sustained.':'Continue 3 h deep study (including 15 min hand work and 30 min coding), 1 h broad/retrieval practice and 2 h papers. Optional revision remains separate.'}</p></div><div className="hub-grid three"><article className="hub-card"><h3>Every week</h3><p>One architecture reconstruction, one small implementation, one spoken interview drill and one hypothesis worth checking. Use existing study blocks.</p></article><article className="hub-card"><h3>Every month</h3><p>Repeat the fast-track topics at a higher depth, run one full mock, revisit fragile mathematics, and refresh selected frontier papers from primary sources.</p></article><article className="hub-card"><h3>Every quarter</h3><p>Review your research direction, completed experiments and remaining gaps. Retire low-value routines; keep the parts that improve reasoning.</p></article></div><h3>Free reference shelf</h3><div className="hub-links">{[['Mathematics and deep learning','https://d2l.ai/'],['PyTorch fundamentals','https://docs.pytorch.org/tutorials/beginner/basics/intro.html'],['Modern NLP','https://web.stanford.edu/class/cs224n/'],['Computer vision','https://szeliski.org/Book/'],['LLM implementation','https://huggingface.co/learn/llm-course/chapter1/1'],['Agents course','https://huggingface.co/learn/agents-course/unit0/introduction'],['Workflows and agents','https://www.anthropic.com/engineering/building-effective-agents'],['Algorithms','https://jeffe.cs.illinois.edu/teaching/algorithms/']].map(([name,url])=><a key={name} href={url} target="_blank" rel="noreferrer">{name} ↗</a>)}</div><p className="hub-muted">No paid course, model API or subscription is required for the hub. External resources can change; use the linked free material selectively.</p></>}
 </main><footer className="hub-footer"><div><b>Your work stays in this browser.</b><p>Export regularly. Files opened locally may have browser-dependent storage; keep the same file location. There is no automatic cross-device sync. Existing ChatGPT-hosted notes are not automatically migrated.</p></div><div className="hub-buttons"><button disabled={!loaded} onClick={exportAll}>Export entire hub</button><label className="hub-import">Restore entire hub<input aria-label="Restore entire hub" type="file" accept=".json,application/json" onChange={e=>{void restore(e.target.files?.[0]);e.target.value=''}}/></label></div></footer></div>
}
