import {useEffect,useState} from 'react';
import topics from './topics.json';
import content from './content.json';
import {readReview,startReview,finishReview,setFragile,isDue,todayLocal,NORMAL,FRAGILE,type Review} from './review';
type Data=Record<string,string|number|boolean>;
const subjects=['All','ML','DL','NLP','CV','DSA','DBMS','CN','Advanced'];
const filters=['All topics','Due for review','Core gaps','Fragile','Not started','Shaky','Solid'];
export default function Topics({data,save,loaded,openHand,openArchitecture}:{data:Data;save:(k:string,v:string)=>void;loaded:boolean;openHand:()=>void;openArchitecture:()=>void}){
 const [subject,setSubject]=useState('All'),[filter,setFilter]=useState('All topics'),[query,setQuery]=useState(''),[selected,setSelected]=useState(topics[0].id),[mode,setMode]=useState('Fast · 1 hour'),[pane,setPane]=useState('Topic index'),[day,setDay]=useState(todayLocal),[seconds,setSeconds]=useState(120),[running,setRunning]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{const timer=setInterval(()=>setDay(todayLocal()),30000);const focus=()=>setDay(todayLocal());window.addEventListener('focus',focus);return()=>{clearInterval(timer);window.removeEventListener('focus',focus)}},[]);
 useEffect(()=>{if(!running)return;const end=Date.now()+seconds*1000;const timer=setInterval(()=>{const left=Math.max(0,Math.ceil((end-Date.now())/1000));setSeconds(left);if(!left)setRunning(false)},250);return()=>clearInterval(timer)},[running]);
 const state=(id:string)=>readReview(data['topic:'+id],topics.find(t=>t.id===id)?.core);
 const count=(f:string)=>topics.filter(t=>matches(state(t.id),f)).length;
 function matches(r:Review,f:string){return f==='All topics'||f==='Due for review'&&isDue(r,day)||f==='Core gaps'&&r.core&&r.status!=='Solid'||f==='Fragile'&&r.fragile||f===r.status}
 const visible=topics.filter(t=>(subject==='All'||t.subject===subject)&&matches(state(t.id),filter)&&`${t.title} ${t.section} ${t.fast} ${t.deep} ${t.drills.join(' ')}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>filter==='Due for review'?state(a.id).due.localeCompare(state(b.id).due):0);
 const topic=visible.find(t=>t.id===selected)??visible[0];
 const r=topic?state(topic.id):null;
 useEffect(()=>{setNotice('');setRunning(false);setSeconds(120)},[topic?.id]);
 function put(next:Review){if(topic)save('topic:'+topic.id,JSON.stringify(next));}
 function begin(){if(!r)return;put(startReview(r));setSeconds(120);setRunning(false);setNotice('Fresh review started. Try all three prompts without notes; tick each after attempting it.');}
 function rate(rating:'Shaky'|'Solid'){if(!r)return;try{put(finishReview(r,rating,day));setRunning(false);setNotice('Review recorded. Open Due for review to find your next topic.')}catch(e){setNotice(String(e))}}
 return <section className="topic-space"><div className="hub-section-head"><div><p className="hub-kicker">CHOOSE A CONCEPT, NOT A DATE</p><h2>Your preparation, by topic.</h2><p>56 topics · seven core subjects + advanced research · every topic is open today.</p></div><button className="hub-action" onClick={()=>{setPane('Topic index');setFilter('Due for review');setSubject('All');setQuery('')}}>Due for review · {count('Due for review')}</button></div>
 <div className="topic-summary"><span><b>{count('Solid')} / {topics.length}</b> self-rated solid</span><progress aria-label="Topics self-rated solid" max={topics.length} value={count('Solid')}/><span>{count('Fragile')} fragile · {count('Not started')} not started</span></div>
 <div className="hub-buttons topic-panes">{['Topic index','Original deep sessions','Original fast sessions'].map(p=><button key={p} aria-pressed={pane===p} onClick={()=>setPane(p)}>{p}</button>)}</div>
 {pane!=='Topic index'?<><p className="hub-callout">The original curriculum is also available without choosing a date. These session notes are separate from topic mastery; calendar checkmarks are unchanged.</p><label className="hub-field">Search sessions<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="hub-grid two">{pane==='Original deep sessions'?content.lessons.map((l,i)=>`${l.title} ${l.group} ${l.goal}`.toLowerCase().includes(query.toLowerCase())&&<article className="hub-card" key={i}><span className="hub-pill">{l.group}</span><h3>{l.title}</h3><p>{l.goal}</p><a href={l.url} target="_blank" rel="noreferrer">Original resource ↗</a><p><b>Coding:</b> {l.code}</p><button onClick={()=>{setPane('Topic index');setQuery('');setSubject('All');setFilter('All topics')}}>Browse related topic resources</button></article>):content.fast.map((f,i)=>f.toLowerCase().includes(query.toLowerCase())&&<article className="hub-card" key={f}><span className="hub-pill amber">FAST SESSION {i+1}</span><h3>{f}</h3><p>10 min cold recall · 35 min selective reading · 15 min explanation aloud.</p><button onClick={()=>{setPane('Topic index');setQuery('');setFilter('All topics');setSubject(i===17||i===18?'DSA':i===19||i===20?'DBMS':i===21?'CN':'All')}}>Choose a topic and its resources →</button></article>)}</div></>:<>
 <div className="topic-toolbar"><label className="hub-field">Search topics and spoken prompts<input type="search" value={query} placeholder="Try positional, SIFT, subnetting…" onChange={e=>setQuery(e.target.value)}/></label><label className="hub-field">Review filter<select value={filter} onChange={e=>setFilter(e.target.value)}>{filters.map(f=><option key={f}>{f}</option>)}</select></label><button onClick={()=>{setQuery('');setFilter('All topics');setSubject('All')}}>Clear filters</button></div>
 <div className="hub-buttons topic-subjects" aria-label="Subjects">{subjects.map(s=><button key={s} aria-pressed={subject===s} onClick={()=>setSubject(s)}>{s==='Advanced'?'Advanced / research':s}</button>)}</div>
 <div className="topic-layout"><aside className="hub-card topic-list" aria-label="Topic list"><p>{visible.length} matching topics</p>{visible.map(t=>{const x=state(t.id);return <button key={t.id} aria-pressed={topic?.id===t.id} onClick={()=>{setSelected(t.id);setRunning(false);setSeconds(120);setNotice('')}}><small>{t.subject} · {x.status}{x.fragile?' · fragile':''}</small><strong>{t.title}</strong><small>{isDue(x,day)?`Due ${x.due}`:x.due?`Revisit ${x.due}`:'No review yet'}</small></button>})}</aside>
 {topic&&r?<article className="hub-card topic-detail" key={topic.id}><span className="hub-pill">{topic.subject}</span><h3>{topic.title}</h3><p className="hub-muted">Focus: {topic.section}</p><div className="hub-buttons"><label className="hub-check"><input type="checkbox" disabled={!loaded} checked={r.core} onChange={e=>put({...r,core:e.target.checked})}/>My core gap</label><label className="hub-check"><input type="checkbox" disabled={!loaded} checked={r.fragile} onChange={e=>put(setFragile(r,e.target.checked))}/>Fragile / slide-only</label></div>
 <div className="hub-buttons topic-panes">{['Fast · 1 hour','Deep · 3 hours'].map(m=><button key={m} aria-pressed={mode===m} onClick={()=>setMode(m)}>{m}</button>)}</div>
 {mode.startsWith('Fast')?<div className="topic-study"><h4>Outcome for this pass</h4><p>{topic.fast}.</p><p>10 min recall → 35 min on one selected resource → 15 min teach-back. Use the spoken prompts below to find gaps.</p></div>:<div className="topic-study"><h4>Derive, implement, explain</h4><p>{topic.deep}.</p><p><b>30-minute coding task:</b> {topic.code}.</p><p>15 min recall · 15 min by hand · 60 min learning · 40 min worked problems · 30 min coding · 20 min teach-back. Split across days if needed.</p><div className="hub-buttons"><button onClick={openHand}>Hand exercises</button><button onClick={openArchitecture}>Architecture investigation</button></div></div>}
 <details className="topic-resources" open><summary>Resources for this topic · choose one first</summary><p>Use the focus section above within these resources. Some links open a course index; the label states whether it is a textbook, course or implementation reference.</p>{topic.resources.map((s,i)=><div className="topic-resource" key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{i+1}. {s.title} ↗</a><small>{s.use}</small></div>)}<p className="hub-muted">Free linked material; buying the associated books is optional. Resource entry pages checked September 2026. Paper and model versions are examples, not a live ranking of the latest systems.</p></details>
 <section className="topic-review"><h3>Say it aloud, closed-book.</h3><p>No recording or AI grading. Checkmarks mean “attempted aloud”; rate the quality honestly after all three prompts.</p><div className="hub-buttons"><button className="hub-action" disabled={!loaded} onClick={begin}>Start new review</button><b>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</b><button disabled={!r.active} onClick={()=>{if(seconds===0)setSeconds(120);setRunning(!running)}}>{running?'Pause timer':'2-minute spoken timer'}</button></div>
 {!r.active&&<p className="hub-muted">Start a new review to clear previous checkmarks and enable fresh attempts. Notes and history are retained.</p>}{topic.drills.map((q,i)=><label className="hub-check" key={q}><input type="checkbox" disabled={!loaded||!r.active} checked={r.checks[i]} onChange={e=>put({...r,checks:r.checks.map((x,j)=>j===i?e.target.checked:x)})}/><span>{q}</span></label>)}
 <div className="hub-buttons topic-rating"><button disabled={!loaded||!r.active||!r.checks.every(Boolean)} onClick={()=>rate('Shaky')}>Shaky — retry tomorrow</button><button className="hub-action" disabled={!loaded||!r.active||!r.checks.every(Boolean)} onClick={()=>rate('Solid')}>Solid — schedule next review</button></div><p role="status">{r.status} · {r.stage>=0?`Stage ${r.stage+1} · ${isDue(r,day)?'Due':'Next review'} ${r.due}`:'No review scheduled yet'}</p>{notice&&<p className="hub-callout">{notice}</p>}
 <details><summary>How the review schedule works</summary><p>Intervals after successful due reviews: normal {NORMAL.join(' / ')} days; fragile {FRAGILE.join(' / ')} days. These are gaps from the review date, not cumulative offsets. The final gap repeats. Shaky resets to stage 1 and tomorrow. Early successful practice keeps the existing due date and stage; repeated clicks cannot advance it. Fragile tagging can shorten, but never postpone, an existing due date.</p><p>Due dates are advisory calendar days in your local timezone. Sundays and breaks do not block access or create required work; resume when available. Only topics you have reviewed enter this queue. This is a study heuristic, not a validated memory model.</p></details>
 <label className="hub-field">Topic notes and explanation gaps<textarea disabled={!loaded} maxLength={12000} value={r.notes} placeholder="What could you not explain? What will you derive or test next?" onChange={e=>put({...r,notes:e.target.value})}/></label>
 {r.history.length>0&&<details><summary>Recent review history ({r.history.length})</summary><ul>{r.history.slice().reverse().map((h,i)=><li key={i}>{h.date} · {h.rating}</li>)}</ul></details>}</section></article>:<article className="hub-card"><h3>{filter==='Due for review'?'No reviews due in this selection.':'No matching topics.'}</h3><p>{filter==='Due for review'?'Start with a core gap or an unreviewed topic. A completed spoken review creates its first due date.':'Change the subject, search or review filter.'}</p><button onClick={()=>{setFilter('All topics');setSubject('All');setQuery('')}}>Show all topics</button></article>}
 </div></>}
 </section>
}
